{% set name = "xeus-python-shell" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-shell/archive/refs/tags/{{ version }}.tar.gz
  sha256: d883121f435d90c4d48247f649166f663658c764928f39cc89e5e7af5c77f2ed

build:
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - echo "tests in outputs"

outputs:
  - name: xeus-python-shell-raw
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
      run_constrained:
        - debugpy >=1.4,<2
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - xeus_python_shell

  - name: xeus-python-shell
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("xeus-python-shell-raw", exact=True) }}
        - ipython  >=7.21,<9
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - xeus_python_shell

about:
  home: https://github.com/jupyter-xeus/xeus-python-shell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xeus-python core python logic.
  dev_url: https://github.com/jupyter-xeus/xeus-python-shell

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
